name: prismatic_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  background_location:
  flutter_foreground_task: ^3.8.0
  http: ^0.13.3
  workmanager: ^0.4.1
  get: 4.3.0
  shared_preferences: ^2.0.13
  geolocator: ^9.0.2
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.0
  restart_app: ^1.1.0
  onesignal_flutter: ^3.3.0
  flutter_fgbg: ^0.2.0
  flutter_background_service: ^2.0.0
  image_picker: ^0.8.3+3
  auto_size_text: ^3.0.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/
